"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const errorHandler_1 = require("../errorHandler");
const products_1 = require("../controllers/products");
const auth_1 = require("../middlewares/auth");
const requireRole_1 = require("../middlewares/requireRole");
const productsRoute = (0, express_1.Router)();
productsRoute.post('/', auth_1.authMiddleware, (0, requireRole_1.isAuthorised)(['ADMIN']), (0, errorHandler_1.errorHandler)(products_1.createProduct));
productsRoute.put("/:id", auth_1.authMiddleware, (0, requireRole_1.isAuthorised)(["ADMIN"]), (0, errorHandler_1.errorHandler)(products_1.updateProduct));
productsRoute.delete("/:id", auth_1.authMiddleware, (0, requireRole_1.isAuthorised)(["ADMIN"]), (0, errorHandler_1.errorHandler)(products_1.deleteProduct));
productsRoute.get('/', auth_1.authMiddleware, (0, errorHandler_1.errorHandler)(products_1.listProducts));
productsRoute.get('/search', auth_1.authMiddleware, (0, errorHandler_1.errorHandler)(products_1.searchProducts));
productsRoute.get('/:id', auth_1.authMiddleware, (0, errorHandler_1.errorHandler)(products_1.getProductById));
exports.default = productsRoute;
